name: Publish linter

on: push

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          cache: "yarn"
      - run: npm run build
      - run: npm publish --dry-run ./javascript/packages/linter
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}